FROM mariadb:10.3

ADD landingAndIntegrationZone.sql /tmp/dump.sql

#RUN sleep 5 && \
#    mysql -u root -p root -e "CREATE DATABASE database_project" && \
#    mysql -u root -p root database_project < /tmp/dump.sql
